# Generated by Django 2.2 on 2020-11-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('genres', models.CharField(default='', max_length=100)),
                ('writer', models.CharField(default='', max_length=100)),
                ('isbn', models.IntegerField(default=0)),
                ('publisher', models.CharField(default='', max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('page_num', models.IntegerField(default=0)),
                ('pub_year', models.IntegerField(default=0)),
            ],
        ),
    ]
